# Generated by Django 5.0.4 on 2024-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(default=None)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=500)),
                ('location', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('not_submitted', 'not_submitted')], default='not_submitted', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lost_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(default=None)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=500)),
                ('location', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('recieved', 'recieved'), ('not_recieved', 'not_recieved')], default='not_recieved', max_length=100)),
            ],
        ),
    ]
