# Generated by Django 5.0.4 on 2024-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_found_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found_item',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
