# Generated by Django 5.0.4 on 2024-04-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_found_item_phone_no_alter_lost_item_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found_item',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
