# Generated by Django 5.0.4 on 2024-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_found_item_image_remove_lost_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lost_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
