# Generated by Django 5.0.4 on 2024-04-06 22:42

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_found_item_name_alter_found_item_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lost_item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='found_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.found_item_image_path),
        ),
        migrations.AlterField(
            model_name='lost_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.lost_item_image_path),
        ),
    ]
