# Generated by Django 4.2.7 on 2024-04-06 23:13

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_alter_found_item_name_alter_found_item_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="found_item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=student.models.found_item_image_path
            ),
        ),
        migrations.AlterField(
            model_name="found_item",
            name="status",
            field=models.CharField(
                choices=[("not_received", "Not Received"), ("received", "Received")],
                default="not_submitted",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="lost_item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=student.models.lost_item_image_path
            ),
        ),
        migrations.AlterField(
            model_name="lost_item",
            name="status",
            field=models.CharField(
                choices=[("not_received", "Not Received"), ("received", "Received")],
                default="not_recieved",
                max_length=100,
            ),
        ),
    ]
