# Generated by Django 5.0.4 on 2024-04-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_found_item_image_alter_found_item_status_and_more'),
        ('student', '0010_lost_item_user'),
    ]

    operations = [
    ]
