# Generated by Django 4.2.7 on 2024-04-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=200)),
                ("enrolment_no", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
    ]
