# Generated by Django 4.2.7 on 2024-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrolment_no",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
