# Generated by Django 4.2.7 on 2024-04-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_student_enrolment_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Organisation_name", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=256)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
    ]
